---
sidebar: sidebar 
permalink: faq-cloud-tiering.html 
keywords: faq, questions, requirements, service connector, object store, object storage, aws, azure, bucket, cluster, aggregate, s3, storage class, standard, inactive data reporting, auto, volume tiering policy, policy, tiering policy, snapshot, cold, inactive, infrequent 
summary: 如果您只是想要快速回答問題、這個常見問題集就能幫上忙。 
---
= BlueXP 分層技術常見問題集
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== BlueXP 分層服務

下列常見問題集與 BlueXP 分層運作方式有關。



=== 使用 BlueXP 分層服務有哪些好處？

BlueXP 分層解決資料快速成長所帶來的挑戰、提供您下列優點：

* 輕鬆將資料中心延伸至雲端、提供最多50倍的空間
* 儲存最佳化、平均節省70%的儲存空間
* 整體擁有成本平均降低30%
* 無需重新調整應用程式的係數




=== 哪種資料可用於分層至雲端？

基本上、在一線和二線儲存系統上、任何被視為非作用中的資料、都是移至雲端的理想目標。在主要系統上、這類資料可能包括快照、歷史記錄和完成的專案。在二線系統上、這包括所有包含為DR和備份目的所製作之主要資料複本的磁碟區。



=== 我可以將NAS磁碟區和SAN磁碟區的資料分層嗎？

是的、您可以將資料從NAS磁碟區分層到公有雲或私有雲、例如StorageGRID ：在分層SAN傳輸協定存取的資料時、NetApp建議使用私有雲端、因為SAN傳輸協定比NAS更敏感地處理連線問題。



=== 非作用中資料或不常使用的資料定義為何？如何控制？

也可以稱為Cold資料的定義是：「已有一段時間未存取的Volume區塊（中繼資料除外）」。「時間量」是由名為「冷卻天數」的分層原則屬性所決定。



=== BlueXP 分層是否能保留我在雲端層節省的儲存效率？

是的、ONTAP 將資料移至雲端層時、會保留諸如壓縮、重複資料刪除和壓縮等功能的不同步磁碟區層級儲存效率。



=== FabricPool 與 BlueXP 分層有何不同？

FabricPool 是 ONTAP 分層技術、可透過 ONTAP CLI 和系統管理員自我管理、或透過 BlueXP 分層管理、以服務形式管理。BlueXP 分層功能可在 ONTAP 和雲端上、透過進階的自動化程序、將 FabricPool 轉變成託管服務、提供更高的可見度、並可控制混合式和多雲端部署之間的分層。



=== 分層至雲端的資料是否可用於災難恢復或備份/歸檔？

不可以由於磁碟區的中繼資料永遠不會從效能層分層、因此無法直接存取儲存在物件儲存設備中的資料。

不過、 BlueXP 分層功能可在次要系統和 SnapMirror 目的地磁碟區（ DP 磁碟區）上啟用、以達到具成本效益的備份和 DR 、進而分層排除所有資料（不含中繼資料）、進而減少資料中心佔用空間和 TCO 。



=== BlueXP 分層是套用在磁碟區或集合體層級？

將分層原則與每個磁碟區建立關聯、即可在磁碟區層級啟用 BlueXP 分層功能。冷資料識別是在區塊層級完成。



=== BlueXP 分層如何判斷要分層到雲端的區塊？

與磁碟區相關的分層原則、是控制哪些區塊分層及何時分層的機制。原則定義資料區塊類型（快照、使用者資料或兩者）和冷卻期間。請參閱 link:concept-cloud-tiering.html#volume-tiering-policies["Volume分層原則"] 以取得詳細資料。



=== BlueXP 分層如何影響磁碟區容量？

BlueXP 分層對磁碟區的容量沒有影響、而是對彙總的效能層使用率有影響。



=== BlueXP 分層是否能啟用非使用中的資料報告？

是的、 BlueXP 分層可在每個集合上啟用非使用中資料報告（ IDR ）。此設定可讓我們識別可分層至低成本物件儲存的非使用中資料量。



=== 從我開始執行資訊起、需要多久的時間才能顯示資訊？

在經過設定的冷卻期間之後、印尼盾會開始顯示資訊。使用更新版本的更新版本時、印尼盾的冷卻時間不可調整為31天。ONTAP從功能表9.8開始ONTAP 、最多可設定183天的印尼盾冷卻期。



== 授權與成本

下列常見問題集與使用 BlueXP 分層的授權和成本有關。



=== 使用 BlueXP 分層成本有多少？

將冷資料分層至公有雲時：

* 針對隨用隨付（PAYGO）、使用型訂閱：每GB每月$05。
* 每年（BYOL）的定期訂閱：每月每GB $0.033起。


https://bluexp.netapp.com/pricing["請參閱定價詳細資料"]。

將冷資料分層至NetApp StorageGRID 的整個系統（私有雲端）、完全不需花費任何成本。



=== 我是否能同時擁有相同ONTAP 的__LW_Y1_cluster的BYOL和PAYGO授權？

是的。BlueXP 分層功能可讓您使用 BYOL 授權、 PAYGO 訂閱或兩者的組合。



=== 如果我達到 BYOL 容量上限，或是 BYOL 授權過期，會發生什麼事？

如果您達到 BYOL 容量上限，或是 BYOL 授權過期，新冷資料的分層就會停止，新冷資料的分層也會停止。所有先前的階層式資料仍可存取、這表示您可以擷取及使用此資料。擷取後、此資料會從雲端移回效能層。

不過、如果您訂閱了 PAYGO 市場訂閱的 _BlueXP - 部署與管理雲端資料服務 _ 、新的 Cold 資料將會繼續分層至物件儲存、您將會根據每次使用的情況支付這些費用。



=== BlueXP 分層授權是否包含雲端供應商的出口費用？

不、這不是。



=== 內部部署系統的重組是否會受到雲端供應商的外出成本影響？

是的。所有從公有雲讀取的內容均需支付出口費用。



=== 我該如何預估雲端費用？BlueXP 分層是否有「假設」模式？

估算雲端供應商託管資料的費用、最好的方法是使用計算機： https://calculator.aws/#/["AWS"]、 https://azure.microsoft.com/en-us/pricing/calculator/["Azure"] 和 https://cloud.google.com/products/calculator["Google Cloud"]。



=== 雲端供應商是否會額外收取從物件儲存設備讀取/擷取資料到內部儲存設備的費用？

是的。檢查 https://aws.amazon.com/s3/pricing/["Amazon S3定價"]、 https://azure.microsoft.com/en-us/pricing/details/storage/blobs/["區塊Blob定價"]和 https://cloud.google.com/storage/pricing["雲端儲存設備定價"] 以取得資料讀取/擷取所產生的額外價格。



=== 在啟用 BlueXP 分層之前、我要如何預估磁碟區的節約效益並取得冷資料報告？

若要取得預估、只要將 ONTAP 叢集新增至 BlueXP 、然後透過 BlueXP 分層叢集頁面進行檢查即可。按一下 * 計算叢集的潛在分層節約 * 以啟動 https://bluexp.netapp.com/cloud-tiering-service-tco["BlueXP 分層 TCO 計算機"^] 看看您可以省下多少錢。



== ONTAP

下列問題 ONTAP 與不相關。



=== BlueXP 分層支援哪些 ONTAP 版本？

BlueXP 分層支援 ONTAP 9.2 版及更新版本。



=== 支援哪些類型的不完整系統？ONTAP

單節點和高可用度 AFF 、 FAS 和 ONTAP Select 叢集均支援 BlueXP 分層。也支援採用鏡射鏡射組態和不完整的叢集FabricPool 組態。MetroCluster



=== 我可以僅使用FAS HDD來分層來自於各種不知道的系統的資料嗎？

是的、從ONTAP 功能區9.8開始、您可以從HDD集合體上裝載的磁碟區分層資料。



=== 我可以將AFF 資料從連接到叢集的不整合式資料分層FAS 、使其具有HDD的不整節點嗎？

是的。BlueXP 分層可設定為在任何集合上託管的階層式磁碟區。資料分層組態與所使用的控制器類型以及叢集是否為異質無關。



=== 關於此功能呢 Cloud Volumes ONTAP ？

如果您有 Cloud Volumes ONTAP 系統、您可以在 BlueXP 分層叢集頁面中找到它們、以便您完整檢視混合雲基礎架構中的資料分層。不過、 Cloud Volumes ONTAP 系統是 BlueXP 分層的唯讀系統。您無法在 BlueXP 分層的 Cloud Volumes ONTAP 上設定資料分層。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html["您可以在 BlueXP 的工作環境中設定 Cloud Volumes ONTAP 系統的分層"^]。



=== 我的叢集還需要哪些其他需求ONTAP ？

這取決於您分層 Cold 資料的位置。如需詳細資料、請參閱下列連結：

* link:task-tiering-onprem-aws.html#prepare-your-ontap-cluster["將資料分層至Amazon S3"]
* link:task-tiering-onprem-azure.html#preparing-your-ontap-clusters["將資料分層至Azure Blob儲存設備"]
* link:task-tiering-onprem-gcp.html#preparing-your-ontap-clusters["將資料分層儲存至Google Cloud Storage"]
* link:task-tiering-onprem-storagegrid.html#preparing-your-ontap-clusters["將資料分層至StorageGRID 物件"]
* link:task-tiering-onprem-s3-compat.html#preparing-your-ontap-clusters["將資料分層至S3物件儲存設備"]




== 物件儲存

下列問題與物件儲存有關。



=== 支援哪些物件儲存供應商？

BlueXP 分層支援下列物件儲存供應商：

* Amazon S3
* Microsoft Azure Blob
* Google Cloud Storage
* NetApp StorageGRID
* S3相容的物件儲存設備（例如MinIO）
* IBM Cloud Object Storage（FabricPool 必須使用System Manager或ONTAP CLI執行此功能的不實組態）




=== 我可以使用自己的桶 / 容器嗎？

是的、您可以。當您設定資料分層時、可以選擇新增庫位 / 容器、或是選取現有的庫位 / 容器。



=== 支援哪些地區？

* link:reference-aws-support.html["支援的 AWS 區域"]
* link:reference-azure-support.html["支援的 Azure 地區"]
* link:reference-google-support.html["支援的 Google Cloud 地區"]




=== 支援哪些 S3 儲存類別？

BlueXP 分層支援資料分層至 _ 標準 _ 、 _ 標準不常用存取 _ 、 _ 單一區域不常用存取 _ 、 _ 智慧分層 _ 及 _ Glacier Instant Retriev_ 儲存類別。請參閱 link:reference-aws-support.html["支援的 S3 儲存類別"] 以取得更多詳細資料。



=== 為什麼 BlueXP 分層不支援 Amazon S3 Glacier Flexible 和 S3 Glacier Deep Archive ？

Amazon S3 Glacier Flexible 和 S3 Glacier Deep Archive 不受支援的主要原因是 BlueXP 分層設計為高效能分層解決方案、因此資料必須持續可用、且可快速存取以供擷取。有了S3 Glacier Flexible和S3 Glacier Deep歸檔、資料擷取可在數分鐘到48小時之間的任何地方進行。



=== 我可以使用其他相容 S3 的物件儲存服務、例如 MinIO 、搭配 BlueXP 分層功能嗎？

是的、叢集使用ONTAP 的是支援透過分層UI設定S3相容的物件儲存設備、這些叢集使用的是更新版本的版本。 link:task-tiering-onprem-s3-compat.html["請參閱此處的詳細資料"]。



=== 支援哪些 Azure Blob 存取層？

BlueXP 分層支援將資料分層至 _hot_ 或 _cool 存取層、以供您的非作用中資料使用。請參閱 link:reference-azure-support.html["支援的 Azure Blob 存取層"] 以取得更多詳細資料。



=== Google Cloud Storage 支援哪些儲存類別？

BlueXP 分層支援資料分層至 _Standard_ 、 _Nearlin_ 、 _Coldlinle_ 及 _Archive_ 儲存類別。請參閱 link:reference-google-support.html["支援的Google Cloud儲存類別"] 以取得更多詳細資料。



=== BlueXP 分層是否支援生命週期管理原則的使用？

是的。您可以啟用生命週期管理、讓 BlueXP 分層將資料從預設的儲存類別 / 存取層移轉到特定天數後更具成本效益的層級。生命週期規則適用於 Amazon S3 和 Google Cloud 儲存設備所選儲存區中的所有物件、以及 Azure Blob 所選儲存帳戶中的所有容器。



=== BlueXP 分層會對整個叢集使用一個物件存放區、還是每個集合使用一個物件存放區？

在典型組態中、整個叢集有一個物件存放區。自2022年8月起、您可以使用*進階設定*頁面新增叢集的其他物件存放區、然後將不同的物件存放區附加至不同的集合體、或將2個物件存放區附加至集合體以進行鏡射。



=== 是否可以將多個儲存區附加至同一個Aggregate？

為了鏡射、每個集合最多可附加兩個儲存區、其中冷資料會同步分層至兩個儲存區。這些庫位可以來自不同的供應商和不同的位置。自2022年8月起、您可以使用*進階設定*頁面、將兩個物件存放區附加至單一Aggregate。



=== 是否可以將不同的儲存區附加至同一個叢集中的不同集合體？

是的。一般最佳實務做法是將單一儲存區附加至多個集合體。不過、使用公有雲時、物件儲存服務的IOPS限制最大、因此必須考量多個儲存區。



=== 當您將磁碟區從一個叢集移轉到另一個叢集時、階層式資料會有什麼影響？

將磁碟區從一個叢集移轉至另一個叢集時、所有的冷資料都會從雲端層讀取。目的地叢集上的寫入位置取決於是否已啟用分層、以及來源與目的地磁碟區上使用的分層原則類型。



=== 當您將磁碟區從同一個叢集中的某個節點移至另一個節點時、階層式資料會發生什麼事？

如果目的地Aggregate沒有附加的雲端層、則會從來源Aggregate的雲端層讀取資料、並完全寫入目的地Aggregate的本機層。如果目的地Aggregate具有附加的雲端層、則會從來源Aggregate的雲端層讀取資料、然後先寫入目的地Aggregate的本機層、以利快速轉換。之後、根據所使用的分層原則、將其寫入雲端層。

從ONTAP S地理 資訊9.6開始、如果目的地Aggregate使用與來源Aggregate相同的雲端層、則Cold資料不會移回本機層。



=== 如何將階層式資料重新放回內部部署的效能層級？

回寫通常是針對讀取執行、視分層原則類型而定。在使用完SUR9.8之前ONTAP 、您可以使用_volume mov移動_作業來寫回整個Volume。從ONTAP SFlash 9.8開始、分層使用者介面有選項可以*恢復所有資料*或*恢復作用中的檔案系統*。 link:task-managing-tiering.html#migrating-data-from-the-cloud-tier-back-to-the-performance-tier["瞭解如何將資料移回效能層"]。



=== 以新的AFF/FAS控制器取代現有的AFF/FAS控制器時、階層式資料是否會在內部部署上重新移轉？

不可以在「標頭交換」程序中、唯一需要變更的是集合體的擁有權。在這種情況下、它將會變更為新的控制器、而不會有任何資料移動。



=== 我可以使用雲端供應商的主控台或物件儲存資源探查器來查看階層至儲存庫的資料嗎？我是否可以直接使用儲存在物件儲存區中的資料、而無需ONTAP 使用任何功能？

不可以建構並分層至雲端的物件不包含單一檔案、但最多可包含1、024個4 KB區塊、可與多個檔案區塊相同。磁碟區的中繼資料永遠保留在本機層上。



== 連接器

下列問題與BlueXP Connector有關。



=== 什麼是Connector？

Connector是在雲端帳戶內或內部部署的運算執行個體上執行的軟體、可讓BlueXP安全地管理雲端資源。若要使用 BlueXP 分層服務、您必須部署 Connector 。



=== 連接器需要安裝在何處？

* 將資料分層至S3時、連接器可位於AWS VPC或內部部署環境中。
* 將資料分層至Blob儲存設備時、Connector可位於Azure vnet或內部部署環境中。
* 將資料分層至Google Cloud Storage時、Connector必須位於Google Cloud Platform VPC中。
* 將資料分層至StorageGRID 不支援功能或其他S3的儲存供應商時、連接器必須位於內部部署環境中。




=== 我可以在內部部署連接器嗎？

是的。Connector軟體可下載並手動安裝在網路中的Linux主機上。 https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["瞭解如何在內部環境中安裝Connector"]。



=== 在使用 BlueXP 分層之前、是否需要雲端服務供應商的帳戶？

是的。您必須擁有帳戶、才能定義要使用的物件儲存設備。在VPC或vnet的雲端上設定Connector時、也需要使用雲端儲存設備供應商的帳戶。



=== 如果連接器故障、會有什麼影響？

如果連接器發生故障、只有階層式環境的可見度會受到影響。所有資料皆可存取、新識別的Cold資料會自動分層至物件儲存設備。



== 分層原則



=== 有哪些可用的分層原則？

有四種分層原則：

* 無：將所有資料歸類為「永遠熱」；防止將磁碟區中的任何資料移至物件儲存設備。
* Cold Snapshot（僅Snapshot）：只有Cold Snapshot區塊會移至物件儲存設備。
* Cold使用者資料和快照（自動）：冷快照區塊和冷使用者資料區塊都會移至物件儲存設備。
* 所有使用者資料（全部）：將所有資料歸類為冷資料；立即將整個磁碟區移至物件儲存設備。


link:concept-cloud-tiering.html#volume-tiering-policies["深入瞭解分層原則"]。



=== 我的資料在哪一點被視為冷資料？

由於資料分層是在區塊層級執行、因此在一段時間內未存取資料區塊、資料區塊就會被視為冷的、這是由分層原則的minimum冷卻天數屬性所定義。適用範圍為ONTAP 2至63天（含更新版本）、更新版本為2至9.7、更新版本則為2至183天（從ONTAP 更新版本9.8開始）。



=== 在資料分層至雲端層之前、資料的預設冷卻期為何？

Cold Snapshot原則的預設冷卻週期為2天、Cold User Data和Snapshot的預設冷卻週期為31天。「冷卻天數」參數不適用於「所有分層」原則。



=== 當我執行完整備份時、是否從物件儲存設備擷取所有階層式資料？

在完整備份期間、會讀取所有的冷資料。資料的擷取取決於所使用的分層原則。使用「All and Cold User Data and Snapshots（全部和冷使用者資料與快照）」原則時、冷資料不會寫入效能層。使用Cold Snapshot原則時、只有在舊快照用於備份時、才會擷取其Cold區塊。



=== 您可以選擇每個Volume的分層大小嗎？

不可以不過、您可以選擇哪些磁碟區符合分層資格、要分層的資料類型及其冷卻期間。這是透過將分層原則與該磁碟區建立關聯來完成。



=== 所有使用者資料原則是否為資料保護磁碟區的唯一選項？

不可以資料保護（DP）磁碟區可與三種可用原則的任一項建立關聯。來源與目的地（DP）磁碟區上使用的原則類型、決定資料的寫入位置。



=== 將磁碟區的分層原則重設為「無」會重新補充冷資料、還是只是防止未來的冷區塊移至雲端？

當分層原則重設時、不會發生重組、但這會防止新的冷區塊移至雲端層。



=== 將資料分層至雲端之後、我可以變更分層原則嗎？

是的。變更後的行為取決於新的關聯原則。



=== 如果我想要確保某些資料不會移至雲端、該怎麼辦？

請勿將分層原則與包含該資料的磁碟區建立關聯。



=== 檔案的中繼資料儲存在何處？

磁碟區的中繼資料永遠儲存在本機、效能層級上、永遠不會分層到雲端。



== 網路與安全性

下列問題與網路和安全性有關。



=== 網路需求為何？

* 此支援叢集可透過連接埠 443 、啟動 HTTPS 連線至您的物件儲存設備供應商。 ONTAP
+
可在物件儲存設備中讀取及寫入資料。 ONTAP物件儲存設備從未啟動、只是回應而已。

* 對於 StorageGRID 僅供使用的物件、 ONTAP 支援使用者指定的連接埠來啟動 HTTPS 連線 StorageGRID 至物件（連接埠可在分層設定期間設定）。
* Connector 需要透過連接埠 443 的輸出 HTTPS 連線、才能連線至 ONTAP 叢集、物件存放區和 BlueXP 分層服務。


如需詳細資料、請參閱：

* link:task-tiering-onprem-aws.html["將資料分層至Amazon S3"]
* link:task-tiering-onprem-azure.html["將資料分層至Azure Blob儲存設備"]
* link:task-tiering-onprem-gcp.html["將資料分層儲存至Google Cloud Storage"]
* link:task-tiering-onprem-storagegrid.html["將資料分層至StorageGRID 物件"]
* link:task-tiering-onprem-s3-compat.html["將資料分層至S3物件儲存設備"]




=== 我可以使用哪些工具來監控和報告、以便管理儲存在雲端的冷資料？

除了 BlueXP 分層、 https://docs.netapp.com/us-en/active-iq-unified-manager/["Active IQ Unified Manager"^] 和 https://docs.netapp.com/us-en/active-iq/index.html["BlueXP 數位顧問"^] 可用於監控和報告。



=== 如果連至雲端供應商的網路連結失敗、會有什麼影響？

萬一網路故障、本機效能層會維持在線上狀態、而且熱資料仍可存取。不過、已經移至雲端層的區塊將無法存取、而應用程式在嘗試存取該資料時會收到錯誤訊息。連線恢復後、所有資料都能無縫存取。



=== 是否有網路頻寬建議？

底層FabricPool 的分層技術讀取延遲取決於雲端層的連線能力。雖然分層可在任何頻寬上運作、但建議將叢集間的生命體放在10 Gbps連接埠上、以提供適當的效能。連接器沒有建議或頻寬限制。

此外、您可以限制在將非使用中資料從磁碟區傳輸到物件儲存區期間所使用的網路頻寬量。設定叢集進行分層時、以及之後從 * 叢集 * 頁面中、可使用 _ 最大傳輸率 _ 設定。



=== 使用者嘗試存取階層式資料時、是否有任何延遲？

是的。雲端層無法提供與本機層相同的延遲、因為延遲取決於連線能力。為了估計物件存放區的延遲和處理量、 BlueXP 分層提供雲端效能測試（根據 ONTAP 物件存放區檔案器）、可在附加物件存放區之後和設定分層之前使用。



=== 我的資料如何受到保護？

AES-256-GCM加密在效能和雲端層均維持不變。TLS 1.2加密可在傳輸至不同層級時、透過線路加密資料、並加密Connector與ONTAP the ors叢 集和物件存放區之間的通訊。



=== 我的支援是否需要在AFF 我的支援上安裝和設定乙太網路連接埠？

是的。叢集間LIF必須在乙太網路連接埠上設定、位於HA配對內的每個節點上、該HA配對會將磁碟區與您計畫分層至雲端的資料裝載在一起。如需詳細資訊、請參閱您計畫分層資料之雲端供應商的需求一節。



=== 需要哪些權限？

* link:task-tiering-onprem-aws.html#set-up-s3-permissions["Amazon需要權限才能管理S3儲存區"]。
* 對於Azure而言、您不需要在需要提供給BlueXP的權限範圍之外額外取得權限。
* link:task-tiering-onprem-gcp.html#preparing-google-cloud-storage["對於Google Cloud、具有儲存存取金鑰的服務帳戶需要儲存管理權限"]。
* link:task-tiering-onprem-storagegrid.html#preparing-storagegrid["若要執行此功能、需要S3權限StorageGRID"]。
* link:task-tiering-onprem-s3-compat.html#preparing-s3-compatible-object-storage["對於S3相容的物件儲存設備、需要S3權限"]。

